
[rule]
author = ["Spencer Brown"]
description = "Insert description here"
from = "now-6m" #default value, change as needed.
name = "Insert name here"
note = "Insert analysis notes here"
risk_score = 47
severity = "medium"
tags = ["Example","Tag"]
type = "eql"
rule_id = "00000000-0000-0000-0000-000000000000"

query = '''
'''

[[rule.threat]] # Example Tactic, Technique, Sub-Technique
framework = "MITRE ATT&CK"
[[rule.threat.technique]]
id = "T1114"
name = "Email Collection"
reference = "https://attack.mitre.org/techniques/T1114/"
[[rule.threat.technique.subtechnique]]
id = "T1114.002"
name = "Remote Email Collection"
reference = "https://attack.mitre.org/techniques/T1114/002/"
[[rule.threat.tactic]]
id = "TA0009"
name = "Collection"
reference = "https://attack.mitre.org/tactics/TA0009/"

# Optional Fields
# throttle: 7d
# version: 1 
# interval: 5m

# [rule.threshold]
# field = ["host.hostname"]
# value = 100