[rule]
author = ["Spencer Brown"]
description = "Detects Nmap and Nikto activity in Zeek HTTP logs."
from = "now-6m" #default value, change as needed.
name = "Web Scanner Activity - Nmap and Nikto"
#note = "Insert analysis notes here"
risk_score = 25
severity = "low"
#tags = ["Example","Tag"]
type = "query"
rule_id = "00000000-0000-0000-0000-000000000002"

query = '''
event.dataset : zeek.http and user.agent.original: *Nmap* or user.agent.original: *Nikto*
'''

[[rule.threat]] # Example Tactic, Technique, Sub-Technique
framework = "MITRE ATT&CK"

[[rule.threat.technique]]
id = "T1046"
name = "Network Service Discovery"
reference = "https://attack.mitre.org/techniques/T1046/"

#[[rule.threat.technique.subtechnique]]
#id = "T1114.002"
#name = "Remote Email Collection"
#reference = "https://attack.mitre.org/techniques/T1114/002/"

[[rule.threat.tactic]]
id = "TA0007"
name = "Discovery"
reference = "https://attack.mitre.org/tactics/TA0007/"

# Optional Fields
# throttle: 7d
# version: 1 
# interval: 5m

# [rule.threshold]
# field = ["host.hostname"]
# value = 100