name: TOML Validation/MITRE Validation

on: 
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  
  toml-mitre-validation:
    
    runs-on: ubuntu-latest
    env:
      API_KEY: ${{ secrets.ELASTIC_KEY }}
    steps:
      
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: '3.11.4'

      - run: pip install requests
      - run: python development/validation.py
      - run : python development/mitre.py
